# Generated by Django 3.2.4 on 2021-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_player_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('batsmen', 'Batsmen'), ('bowler', 'Bowler'), ('all_rounder', 'All_rounder')], max_length=40),
        ),
    ]
