# Generated by Django 3.2.4 on 2021-10-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('batsmen', 'Batsmen'), ('bowler', 'Bowler'), ('batting_all_rounder', 'Batting_all_rounder'), ('bowling_all_rounder', 'bowling_all_rounder'), ('wk_Batsmen', 'WK_Batsmen')], max_length=40),
        ),
    ]
